[package]
name = "rpi-led-matrix"
description = "Bindings for Hzeller RPi-RGB-Led-Matrix"
version = "0.1.1"
authors = ["Vincent Pasquier <vincentpasquier@posteo.net>"]
repository = "https://github.com/helvethor/rust-rpi-rgb-led-matrix"
homepage = "https://github.com/helvethor/rust-rpi-rgb-led-matrix"
build = "build.rs"
license = "GPL-3.0"
readme = "README.md"


[build-dependencies]
gcc = "0.3"

[dependencies]
libc = "0.2"
